/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const FriendshipStatus = IDL.Variant({
  'pending' : IDL.Null,
  'rejected' : IDL.Null,
  'accepted' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const LeetCodeStats = IDL.Record({
  'total' : IDL.Nat,
  'easy' : IDL.Nat,
  'hard' : IDL.Nat,
  'medium' : IDL.Nat,
});
export const CodeChefStats = IDL.Record({ 'totalSolved' : IDL.Nat });
export const Username = IDL.Text;
export const PrincipalArray = IDL.Vec(IDL.Principal);
export const UserProfile = IDL.Record({
  'lastRefreshed' : Time,
  'displayName' : IDL.Text,
  'leetcodeStats' : LeetCodeStats,
  'codechefStats' : CodeChefStats,
  'leetcodeUsername' : Username,
  'codechefUsername' : Username,
  'friends' : PrincipalArray,
});
export const UserProfileInput = IDL.Record({
  'displayName' : IDL.Text,
  'leetcodeUsername' : Username,
  'codechefUsername' : Username,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acceptFriendRequest' : IDL.Func([IDL.Principal], [FriendshipStatus], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFriendStatus' : IDL.Func(
      [IDL.Principal, IDL.Principal],
      [IDL.Opt(FriendshipStatus)],
      ['query'],
    ),
  'getFriends' : IDL.Func([IDL.Principal], [IDL.Vec(UserProfile)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'refreshCodechefStats' : IDL.Func([], [IDL.Opt(CodeChefStats)], []),
  'refreshLeetcodeStats' : IDL.Func([], [IDL.Opt(LeetCodeStats)], []),
  'registerOrUpdateProfile' : IDL.Func([UserProfileInput], [UserProfile], []),
  'rejectFriendRequest' : IDL.Func([IDL.Principal], [FriendshipStatus], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchUsers' : IDL.Func([IDL.Text], [IDL.Vec(UserProfile)], ['query']),
  'sendFriendRequest' : IDL.Func([IDL.Principal], [FriendshipStatus], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const FriendshipStatus = IDL.Variant({
    'pending' : IDL.Null,
    'rejected' : IDL.Null,
    'accepted' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const LeetCodeStats = IDL.Record({
    'total' : IDL.Nat,
    'easy' : IDL.Nat,
    'hard' : IDL.Nat,
    'medium' : IDL.Nat,
  });
  const CodeChefStats = IDL.Record({ 'totalSolved' : IDL.Nat });
  const Username = IDL.Text;
  const PrincipalArray = IDL.Vec(IDL.Principal);
  const UserProfile = IDL.Record({
    'lastRefreshed' : Time,
    'displayName' : IDL.Text,
    'leetcodeStats' : LeetCodeStats,
    'codechefStats' : CodeChefStats,
    'leetcodeUsername' : Username,
    'codechefUsername' : Username,
    'friends' : PrincipalArray,
  });
  const UserProfileInput = IDL.Record({
    'displayName' : IDL.Text,
    'leetcodeUsername' : Username,
    'codechefUsername' : Username,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acceptFriendRequest' : IDL.Func([IDL.Principal], [FriendshipStatus], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFriendStatus' : IDL.Func(
        [IDL.Principal, IDL.Principal],
        [IDL.Opt(FriendshipStatus)],
        ['query'],
      ),
    'getFriends' : IDL.Func([IDL.Principal], [IDL.Vec(UserProfile)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'refreshCodechefStats' : IDL.Func([], [IDL.Opt(CodeChefStats)], []),
    'refreshLeetcodeStats' : IDL.Func([], [IDL.Opt(LeetCodeStats)], []),
    'registerOrUpdateProfile' : IDL.Func([UserProfileInput], [UserProfile], []),
    'rejectFriendRequest' : IDL.Func([IDL.Principal], [FriendshipStatus], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchUsers' : IDL.Func([IDL.Text], [IDL.Vec(UserProfile)], ['query']),
    'sendFriendRequest' : IDL.Func([IDL.Principal], [FriendshipStatus], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };