/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CodeChefStats { 'totalSolved' : bigint }
export type FriendshipStatus = { 'pending' : null } |
  { 'rejected' : null } |
  { 'accepted' : null };
export interface LeetCodeStats {
  'total' : bigint,
  'easy' : bigint,
  'hard' : bigint,
  'medium' : bigint,
}
export type PrincipalArray = Array<Principal>;
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'lastRefreshed' : Time,
  'displayName' : string,
  'leetcodeStats' : LeetCodeStats,
  'codechefStats' : CodeChefStats,
  'leetcodeUsername' : Username,
  'codechefUsername' : Username,
  'friends' : PrincipalArray,
}
export interface UserProfileInput {
  'displayName' : string,
  'leetcodeUsername' : Username,
  'codechefUsername' : Username,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Username = string;
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acceptFriendRequest' : ActorMethod<[Principal], FriendshipStatus>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFriendStatus' : ActorMethod<
    [Principal, Principal],
    [] | [FriendshipStatus]
  >,
  'getFriends' : ActorMethod<[Principal], Array<UserProfile>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'refreshCodechefStats' : ActorMethod<[], [] | [CodeChefStats]>,
  'refreshLeetcodeStats' : ActorMethod<[], [] | [LeetCodeStats]>,
  'registerOrUpdateProfile' : ActorMethod<[UserProfileInput], UserProfile>,
  'rejectFriendRequest' : ActorMethod<[Principal], FriendshipStatus>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchUsers' : ActorMethod<[string], Array<UserProfile>>,
  'sendFriendRequest' : ActorMethod<[Principal], FriendshipStatus>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];